### ISSUE TITLE
TypeError: bot.Client is not a constructor

### ISSUE THREAD

**Issue by TheSpoiledSnail** [RPGTheGreat/lavaplayer#2]
```
const music = new bot.Client(client.config.YOUTUBE_API_KEY)
              ^

TypeError: bot.Client is not a constructor
    at Object.<anonymous> (/home/container/index.js:115:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by RPGTheGreat** [comment]
Fix now
